name: build-with-tag
on:
    workflow_dispatch:


jobs:
    dev-build:
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
                with:
                    ref: 'web-release-1.0.0'

            -   name: github environment
                run: |
                    git_hash=$(git rev-parse --short "$GITHUB_SHA") 
                    echo $git_hash